# Generated by Django 5.2 on 2025-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_userbookingtable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingtable',
            name='payment_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
